/*
class User {
  final int id;
  final String username;
  final String email;
  final String fullName;
  final String phone;
  final String picture;
  final int role;

  User({
    required this.id,
    required this.username,
    required this.email,
    required this.fullName,
    required this.phone,
    required this.picture,
    required this.role,
  });

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'],
      username: json['username'],
      email: json['email'],
      fullName: json['full_name'],
      phone: json['phone'],
      picture: json['picture'],
      role: json['role'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'username': username,
      'email': email,
      'full_name': fullName,
      'phone': phone,
      'picture': picture,
      'role': role,
    };
  }
}*/

class Autogenerated {
  bool? success;
  String? message;
  String? token;
  String? tokenType;
  int? expiresIn;
  User? user;

  Autogenerated(
      {this.success,
        this.message,
        this.token,
        this.tokenType,
        this.expiresIn,
        this.user});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    token = json['token'];
    tokenType = json['token_type'];
    expiresIn = json['expires_in'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['message'] = this.message;
    data['token'] = this.token;
    data['token_type'] = this.tokenType;
    data['expires_in'] = this.expiresIn;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? id;
  String? username;
  String? email;
  Null emailVerifiedAt;
  String? fullName;
  String? phone;
  String? picture;
  int? role;
  String? googleId;
  String? createdAt;
  String? updatedAt;

  User(
      {this.id,
        this.username,
        this.email,
        this.emailVerifiedAt,
        this.fullName,
        this.phone,
        this.picture,
        this.role,
        this.googleId,
        this.createdAt,
        this.updatedAt});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    username = json['username'];
    email = json['email'];
    emailVerifiedAt = json['email_verified_at'];
    fullName = json['full_name'];
    phone = json['phone'];
    picture = json['picture'];
    role = json['role'];
    googleId = json['google_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['username'] = this.username;
    data['email'] = this.email;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['full_name'] = this.fullName;
    data['phone'] = this.phone;
    data['picture'] = this.picture;
    data['role'] = this.role;
    data['google_id'] = this.googleId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
