import 'dart:convert';
import 'package:http/http.dart' as http;
import '../model/model_movie.dart';

class MovieViewModel {
  static Future<List<Data>> fetchMovies(int status) async {
    final response = await http.get(
      Uri.parse('https://lolifashion.social/api/listfilms?type=$status'),
      headers: {'Content-Type': 'application/json'},
    );

    if (response.statusCode == 200) {
      final Map<String, dynamic> jsonResponse = json.decode(response.body);
      final ListMovie listMovie = ListMovie.fromJson(jsonResponse);

      return listMovie.data!;
    } else {
      throw Exception('Failed to load movies');
    }
  }

/// SUA SAU NHE'
// Future<AutoGenerated> searchMovies(String query) async {
//   final response = await http.get(
//     Uri.parse('$searchApiUrl$query'),
//     headers: {
//       'Authorization': apiKey,
//       'accept': 'application/json',
//     },
//   );

//   if (response.statusCode == 200) {
//     return AutoGenerated.fromJson(json.decode(response.body));
//   } else {
//     throw Exception('Failed to search movies');
//   }
// }
}

