import 'dart:convert';
import 'package:rxdart/rxdart.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import '../model/model_ticket.dart';

class TicketsViewModel {
  final _ticketsController = BehaviorSubject<AutogeneratedTickets>();
  final _loadingController = BehaviorSubject<bool>();
  final _errorController = BehaviorSubject<String?>();

  Stream<AutogeneratedTickets> get ticketsStream => _ticketsController.stream;
  Stream<bool> get loadingStream => _loadingController.stream;
  Stream<String?> get errorStream => _errorController.stream;

  Future<void> fetchTickets({
    required String? seatIds,
    required int? showtimeId,
    required int? amount,
  }) async {
    _loadingController.add(true);

    try {
      final prefs = await SharedPreferences.getInstance();
      final token = prefs.getString('token');

      if (token == null) {
        _errorController.add('User is not authenticated.');
        return;
      }

      final url = Uri.parse('https://lolifashion.social/api/purchase?seat_id=$seatIds&showtime_id=$showtimeId&amount=$amount');

      final response = await http.post(
        url,
        headers: {
          'Authorization': 'Bearer $token',
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final tickets = AutogeneratedTickets.fromJson(data);
        _ticketsController.add(tickets);
      } else {
        final error = jsonDecode(response.body)['message'] ?? "Unknown error";
        _errorController.add(error);
      }
    } catch (e) {
      _errorController.add(e.toString());
    } finally {
      _loadingController.add(false);
    }
  }

  void dispose() {
    _ticketsController.close();
    _loadingController.close();
    _errorController.close();
  }
}
