/*
import 'dart:convert';
import 'package:http/http.dart' as http;
import '../../model/model_movie.dart';

class MovieViewModel {
  final String nowPlayingApiUrl =
      'https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1';
  final String comingSoonApiUrl =
      'https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1';
  final String searchApiUrl =
      'https://api.themoviedb.org/3/search/movie?language=en-US&page=1&query=';
  final String apiKey =
      'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZjU2MzQ0ODU5NmYwMDlmMzdiMGQ0NWFiYWJiZWU1MCIsIm5iZiI6MTcyNDIwODM1NS4yNzYsInN1YiI6IjY2YzU1NGUzZGM4MTA0NGVhZjVlYmYyMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.F4L_8k-x1UdCzVx11Msv4UUjC-hXS3Eoyv17pDZltuc';

  Future<AutoGenerated> fetchNowPlayingMovies() async {
    final response = await http.get(
      Uri.parse(nowPlayingApiUrl),
      headers: {
        'Authorization': apiKey,
        'accept': 'application/json',
      },
    );

    if (response.statusCode == 200) {
      return AutoGenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to load now playing movies');
    }
  }

  Future<AutoGenerated> fetchComingSoonMovies() async {
    final response = await http.get(
      Uri.parse(comingSoonApiUrl),
      headers: {
        'Authorization': apiKey,
        'accept': 'application/json',
      },
    );

    if (response.statusCode == 200) {
      return AutoGenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to load coming soon movies');
    }
  }

  Future<AutoGenerated> searchMovies(String query) async {
    final response = await http.get(
      Uri.parse('$searchApiUrl$query'),
      headers: {
        'Authorization': apiKey,
        'accept': 'application/json',
      },
    );

    if (response.statusCode == 200) {
      return AutoGenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to search movies');
    }
  }
}
*/

import 'dart:convert';
import 'package:http/http.dart' as http;
import '../model/model_movie.dart';

class MovieViewModel {
  static Future<List<Data>> fetchMovies(int status) async {
    final response = await http.get(
      Uri.parse('https://lolifashion.social/api/listfilms?type=$status'),
      headers: {'Content-Type': 'application/json'},
    );

    if (response.statusCode == 200) {
      final Map<String, dynamic> jsonResponse = json.decode(response.body);
      final ListMovie listMovie = ListMovie.fromJson(jsonResponse);

      return listMovie.data!;
    } else {
      throw Exception('Failed to load movies');
    }
  }

  /*static Future<List<Data>> fetchShowTimes(int movieId) async {
    final url = Uri.parse('https://lolifashion.social/api/showtimes/film?film_id=$movieId');
    final response = await http.get(url);

    if (response.statusCode == 200) {
      final data = json.decode(response.body);
      return data['data'] ?? [];
    } else {
      throw Exception('Failed to load showtimes');
    }
  }*/

/// SUA SAU NHE'
// Future<AutoGenerated> searchMovies(String query) async {
//   final response = await http.get(
//     Uri.parse('$searchApiUrl$query'),
//     headers: {
//       'Authorization': apiKey,
//       'accept': 'application/json',
//     },
//   );

//   if (response.statusCode == 200) {
//     return AutoGenerated.fromJson(json.decode(response.body));
//   } else {
//     throw Exception('Failed to search movies');
//   }
// }
}

