import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:rxdart/rxdart.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../model/model_tickets_history.dart';

class TicketsHistoryViewModel {
  final _ticketsSubject = BehaviorSubject<DataMyTicketsHistory>();
  final _errorSubject = BehaviorSubject<String>();

  Stream<DataMyTicketsHistory> get ticketsStream => _ticketsSubject.stream;
  Stream<String> get errorStream => _errorSubject.stream;

  Future<void> fetchTicketsHistory() async {
    final url = Uri.parse('https://lolifashion.social/api/ticket_history');

    try {
      final prefs = await SharedPreferences.getInstance();
      final token = prefs.getString('token');

      if (token == null) {
        _errorSubject.add('User is not authenticated.');
        return;
      }

      final response = await http.get(
        url,
        headers: {
          'Accept': 'application/json',
          'Authorization': 'Bearer $token',
        },
      );

      if (response.statusCode == 200) {
        final jsonData = json.decode(response.body);
        final tickets = AutogeneratedTicketsHistory.fromJson(jsonData);
        if (tickets.data != null) {
          _ticketsSubject.add(tickets.data!);
        } else {
          _errorSubject.add('No data found');
        }
      } else {
        _errorSubject.add('Failed to fetch data: ${response.reasonPhrase}');
      }
    } catch (e) {
      _errorSubject.add('An error occurred: $e');
    }
  }

  void dispose() {
    _ticketsSubject.close();
    _errorSubject.close();
  }
}
