import 'package:flutter/material.dart';
import 'package:movies_app_ttcn/widgets/movies/build_movie.dart';

import '../../model/movie_model.dart';
import '../../view/tab_home/viewmodel_home.dart';

class SearchMovieCarousel extends StatelessWidget {
  final String query;

  const SearchMovieCarousel({super.key, required this.query});

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<AutoGenerated>(
      future: MovieViewModel().searchMovies(query),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(
              child: CircularProgressIndicator(
                color: Colors.amber,
              )
          );
        } else if (snapshot.hasError) {
          return Center(
              child: Text(
                  'Error: ${snapshot.error}',
                  style: const TextStyle(color: Colors.white)
              )
          );
        } else if (snapshot.hasData) {
          return SizedBox(
            height: 350,
            child: buildMovieSearch(
                snapshot.data!.results!
            ),
          );
        } else {
          return const Center(
              child: Text(
                  'No data available',
                  style: TextStyle(color: Colors.white)
              )
          );
        }
      },
    );
  }
}
