import 'package:flutter/material.dart';
import 'package:movies_app_ttcn/widgets/select_seat/widget_list_date_time.dart';
import '../../model/seat_model.dart';
import '../../model/seat_repositity.dart';

class ListTime extends StatefulWidget {
  const ListTime({Key? key}) : super(key: key);

  @override
  _ListTimeState createState() => _ListTimeState();
}

class _ListTimeState extends State<ListTime> {
  String selectedTime = '';

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
      future: fetchSeatData(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(
            child: CircularProgressIndicator(color: Colors.amber),
          );
        } else if (snapshot.hasError) {
          return Center(
            child: Text(
              'Error: ${snapshot.error}',
              style: const TextStyle(color: Colors.white),
            ),
          );
        } else if (snapshot.hasData && snapshot.data!.data!.showtime != null) {
          final showtime = snapshot.data!.data!.showtime!;
          return SizedBox(
            height: 50,
            child: buildTimeList(showtime, selectedTime, (time) {
              setState(() {
                selectedTime = time;
              });
            }),
          );
        } else {
          return const Center(
            child: Text(
              'No showtime available',
              style: TextStyle(color: Colors.white),
            ),
          );
        }
      },
    );
  }
}
