import 'package:flutter/material.dart';
import 'package:movies_app_ttcn/widgets/select_seat/widget_list_date_time.dart';
import '../../model/seat_model.dart';
import '../../model/seat_repositity.dart';

class ListDate extends StatefulWidget {
  const ListDate({Key? key}) : super(key: key);

  @override
  _ListDateState createState() => _ListDateState();
}

class _ListDateState extends State<ListDate> {
  String selectedDate = '';

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Autogenerated>(
      future: fetchSeatData(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(
            child: CircularProgressIndicator(color: Colors.amber),
          );
        } else if (snapshot.hasError) {
          return Center(
            child: Text(
              'Error: ${snapshot.error}',
              style: const TextStyle(color: Colors.white),
            ),
          );
        } else if (snapshot.hasData && snapshot.data!.data!.showtime != null) {
          final showtime = snapshot.data!.data!.showtime!;
          return SizedBox(
            height: 104,
            child: buildDateList(showtime, selectedDate, (date) {
              setState(() {
                selectedDate = date;
              });
            }),
          );
        } else {
          return const Center(
            child: Text(
              'No showtime available',
              style: TextStyle(color: Colors.white),
            ),
          );
        }
      },
    );
  }
}
