/*
import 'package:flutter/material.dart';
import 'package:movies_app_ttcn/widgets/select_seat/widget_list_date_time.dart';
import '../../model/model_movie.dart';
import '../../view/tab_home/viewmodel_movie.dart';

class ListDate extends StatelessWidget {
  const ListDate({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<AutoGenerated>(
      future: MovieViewModel().fetchComingSoonMovies(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(
              child: CircularProgressIndicator(
                color: Colors.amber,
              )
          );
        } else if (snapshot.hasError) {
          return Center(
              child: Text(
                  'Error: ${snapshot.error}',
                  style: const TextStyle(color: Colors.white)
              )
          );
        } else if (snapshot.hasData) {
          return SizedBox(
            height: 104,
            child: buildDateList(
                snapshot.data!.results!
            ),
          );
        } else {
          return const Center(
              child: Text(
                  'No data available',
                  style: TextStyle(color: Colors.white)
              )
          );
        }
      },
    );
  }
}
*/
