class AutogeneratedStripe {
  String? status;
  String? clientSecret;

  AutogeneratedStripe({this.status, this.clientSecret});

  AutogeneratedStripe.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    clientSecret = json['client_secret'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['client_secret'] = this.clientSecret;
    return data;
  }
}