class AutogeneratedSeats {
  String? status;
  String? message;
  DataSeats? data;

  AutogeneratedSeats({this.status, this.message, this.data});

  AutogeneratedSeats.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    data = json['data'] != null ? new DataSeats.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class DataSeats {
  int? showtimeId;
  String? filmName;
  String? roomName;
  String? startTime;
  String? day;
  List<Seats>? seats;

  DataSeats(
      {this.showtimeId,
        this.filmName,
        this.roomName,
        this.startTime,
        this.day,
        this.seats});

  DataSeats.fromJson(Map<String, dynamic> json) {
    showtimeId = json['showtime_id'];
    filmName = json['film_name'];
    roomName = json['room_name'];
    startTime = json['start_time'];
    day = json['day'];
    if (json['seats'] != null) {
      seats = <Seats>[];
      json['seats'].forEach((v) {
        seats!.add(new Seats.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['showtime_id'] = this.showtimeId;
    data['film_name'] = this.filmName;
    data['room_name'] = this.roomName;
    data['start_time'] = this.startTime;
    data['day'] = this.day;
    if (this.seats != null) {
      data['seats'] = this.seats!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Seats {
  int? seatId;
  String? seatNumber;
  String? status;

  Seats({this.seatId, this.seatNumber, this.status});

  Seats.fromJson(Map<String, dynamic> json) {
    seatId = json['seat_id'];
    seatNumber = json['seat_number'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['seat_id'] = this.seatId;
    data['seat_number'] = this.seatNumber;
    data['status'] = this.status;
    return data;
  }
}