class AutogeneratedShowTimes {
  String? status;
  String? message;
  List<DataShowTimes>? data;

  AutogeneratedShowTimes({this.status, this.message, this.data});

  AutogeneratedShowTimes.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    if (json['data'] != null) {
      data = <DataShowTimes>[];
      json['data'].forEach((v) {
        data!.add(new DataShowTimes.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DataShowTimes {
  String? date;
  String? time;

  DataShowTimes({this.date, this.time});

  DataShowTimes.fromJson(Map<String, dynamic> json) {
    date = json['date'];
    time = json['time'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['date'] = this.date;
    data['time'] = this.time;
    return data;
  }
}

/*
class Showtime {
  final String date;
  final String time;

  Showtime({required this.date, required this.time});

  factory Showtime.fromJson(Map<String, dynamic> json) {
    return Showtime(
      date: json['date'] as String,
      time: json['time'] as String,
    );
  }
}

class ShowtimeResponse {
  final String status;
  final String message;
  final List<Showtime> data;

  ShowtimeResponse({required this.status, required this.message, required this.data});

  factory ShowtimeResponse.fromJson(Map<String, dynamic> json) {
    var showtimes = (json['data'] as List)
        .map((item) => Showtime.fromJson(item))
        .toList();
    return ShowtimeResponse(
      status: json['status'] as String,
      message: json['message'] as String,
      data: showtimes,
    );
  }
}
*/

