class AutogeneratedPayments {
  String? status;
  String? message;
  DataPayments? data;

  AutogeneratedPayments({this.status, this.message, this.data});

  AutogeneratedPayments.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    data = json['data'] != null ? new DataPayments.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class DataPayments {
  String? orderId;
  int? bookingId;
  String? amount;
  Film? film;
  User? user;
  List<Seats>? seats;
  int? showtimeId;

  DataPayments(
      {this.orderId,
        this.bookingId,
        this.amount,
        this.film,
        this.user,
        this.seats,
        this.showtimeId});

  DataPayments.fromJson(Map<String, dynamic> json) {
    orderId = json['order_id'];
    bookingId = json['booking_id'];
    amount = json['amount'];
    film = json['film'] != null ? new Film.fromJson(json['film']) : null;
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
    if (json['seats'] != null) {
      seats = <Seats>[];
      json['seats'].forEach((v) {
        seats!.add(new Seats.fromJson(v));
      });
    }
    showtimeId = json['showtime_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['order_id'] = this.orderId;
    data['booking_id'] = this.bookingId;
    data['amount'] = this.amount;
    if (this.film != null) {
      data['film'] = this.film!.toJson();
    }
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    if (this.seats != null) {
      data['seats'] = this.seats!.map((v) => v.toJson()).toList();
    }
    data['showtime_id'] = this.showtimeId;
    return data;
  }
}

class Film {
  int? id;
  String? filmName;
  String? thumbnail;
  int? duration;
  double? review;
  String? storyLine;
  String? trailerLink;
  String? movieGenre;
  String? censorship;
  String? language;
  String? director;
  String? actor;
  int? status;
  String? release;

  Film(
      {this.id,
        this.filmName,
        this.thumbnail,
        this.duration,
        this.review,
        this.storyLine,
        this.trailerLink,
        this.movieGenre,
        this.censorship,
        this.language,
        this.director,
        this.actor,
        this.status,
        this.release});

  Film.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    filmName = json['film_name'];
    thumbnail = json['thumbnail'];
    duration = json['duration'];
    review = json['review'];
    storyLine = json['story_line'];
    trailerLink = json['trailer_link'];
    movieGenre = json['movie_genre'];
    censorship = json['censorship'];
    language = json['language'];
    director = json['director'];
    actor = json['actor'];
    status = json['status'];
    release = json['release'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['film_name'] = this.filmName;
    data['thumbnail'] = this.thumbnail;
    data['duration'] = this.duration;
    data['review'] = this.review;
    data['story_line'] = this.storyLine;
    data['trailer_link'] = this.trailerLink;
    data['movie_genre'] = this.movieGenre;
    data['censorship'] = this.censorship;
    data['language'] = this.language;
    data['director'] = this.director;
    data['actor'] = this.actor;
    data['status'] = this.status;
    data['release'] = this.release;
    return data;
  }
}

class User {
  int? userId;
  String? name;
  String? email;

  User({this.userId, this.name, this.email});

  User.fromJson(Map<String, dynamic> json) {
    userId = json['user_id'];
    name = json['name'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['user_id'] = this.userId;
    data['name'] = this.name;
    data['email'] = this.email;
    return data;
  }
}

class Seats {
  int? seatId;
  String? seatNumber;

  Seats({this.seatId, this.seatNumber});

  Seats.fromJson(Map<String, dynamic> json) {
    seatId = json['seat_id'];
    seatNumber = json['seat_number'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['seat_id'] = this.seatId;
    data['seat_number'] = this.seatNumber;
    return data;
  }
}

