class Autogenerated {
  String? status;
  String? message;
  Data? data;

  Autogenerated({this.status, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<Seat>? seat;
  int? col;
  Showtime? showtime;
  Invoice? invoice;

  Data({this.seat, this.col, this.showtime, this.invoice});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['seat'] != null) {
      seat = <Seat>[];
      json['seat'].forEach((v) {
        seat!.add(new Seat.fromJson(v));
      });
    }
    col = json['col'];
    showtime = json['showtime'] != null
        ? new Showtime.fromJson(json['showtime'])
        : null;
    invoice =
    json['invoice'] != null ? new Invoice.fromJson(json['invoice']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.seat != null) {
      data['seat'] = this.seat!.map((v) => v.toJson()).toList();
    }
    data['col'] = this.col;
    if (this.showtime != null) {
      data['showtime'] = this.showtime!.toJson();
    }
    if (this.invoice != null) {
      data['invoice'] = this.invoice!.toJson();
    }
    return data;
  }
}

class Seat {
  int? seatId;
  String? seatNumber;
  String? seatStatus;

  Seat({this.seatId, this.seatNumber, this.seatStatus});

  Seat.fromJson(Map<String, dynamic> json) {
    seatId = json['seat_id'];
    seatNumber = json['seat_number'];
    seatStatus = json['seat_status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['seat_id'] = this.seatId;
    data['seat_number'] = this.seatNumber;
    data['seat_status'] = this.seatStatus;
    return data;
  }
}

class Showtime {
  String? showtimeId;
  String? startTime;
  String? day;

  Showtime({this.showtimeId, this.startTime, this.day});

  Showtime.fromJson(Map<String, dynamic> json) {
    showtimeId = json['showtime_id'];
    startTime = json['start_time'];
    day = json['day'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['showtime_id'] = this.showtimeId;
    data['start_time'] = this.startTime;
    data['day'] = this.day;
    return data;
  }
}

class Invoice {
  String? totalAmount;

  Invoice({this.totalAmount});

  Invoice.fromJson(Map<String, dynamic> json) {
    totalAmount = json['total_amount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['total_amount'] = this.totalAmount;
    return data;
  }
}