import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:movies_app_ttcn/model/seat_model.dart';

Future<Autogenerated> fetchSeatData() async {
  final url = Uri.parse('https://lolifashion.social/api/select_seat');
  try {
    final response = await http.get(url);

    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to load seat data with status: ${response.statusCode}');
    }
  } catch (error) {
    throw Exception('Failed to load seat data: $error');
  }
}

