// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXFsNUy0qQV2Fj7EwRyIS521a21iI45w',
    appId: '1:217942102814:web:a471303648654bd3276f0f',
    messagingSenderId: '217942102814',
    projectId: 'mbooking-c2f31',
    authDomain: 'mbooking-c2f31.firebaseapp.com',
    storageBucket: 'mbooking-c2f31.firebasestorage.app',
    measurementId: 'G-G62WG34CEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvhZblSjJTNR0X106BZ7TijjbqJ3W47MM',
    appId: '1:217942102814:android:6d5e2d685cc0dea8276f0f',
    messagingSenderId: '217942102814',
    projectId: 'mbooking-c2f31',
    storageBucket: 'mbooking-c2f31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-FgP3YBGKBgcHbQ1hTgmN_hhCl1t7xD0',
    appId: '1:217942102814:ios:82a274c688a49265276f0f',
    messagingSenderId: '217942102814',
    projectId: 'mbooking-c2f31',
    storageBucket: 'mbooking-c2f31.firebasestorage.app',
    iosBundleId: 'com.hitoandzzx.moviesAppTtcn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-FgP3YBGKBgcHbQ1hTgmN_hhCl1t7xD0',
    appId: '1:217942102814:ios:82a274c688a49265276f0f',
    messagingSenderId: '217942102814',
    projectId: 'mbooking-c2f31',
    storageBucket: 'mbooking-c2f31.firebasestorage.app',
    iosBundleId: 'com.hitoandzzx.moviesAppTtcn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdXFsNUy0qQV2Fj7EwRyIS521a21iI45w',
    appId: '1:217942102814:web:823cc4de0f4b99b3276f0f',
    messagingSenderId: '217942102814',
    projectId: 'mbooking-c2f31',
    authDomain: 'mbooking-c2f31.firebaseapp.com',
    storageBucket: 'mbooking-c2f31.firebasestorage.app',
    measurementId: 'G-0RTVRE7RV5',
  );
}
