import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:movies_app_ttcn/model/Cinema_model.dart';

class CinemaViewModel {
  final String nowPlayingApiUrl =
      'https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1';
  final String comingSoonApiUrl =
      'https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1';
  final String apiKey =
      'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZjU2MzQ0ODU5NmYwMDlmMzdiMGQ0NWFiYWJiZWU1MCIsIm5iZiI6MTcyNDIwODM1NS4yNzYsInN1YiI6IjY2YzU1NGUzZGM4MTA0NGVhZjVlYmYyMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.F4L_8k-x1UdCzVx11Msv4UUjC-hXS3Eoyv17pDZltuc';

  Future<Autogenerated> fetchNowPlayingMovies() async {
    final response = await http.get(
      Uri.parse(nowPlayingApiUrl),
      headers: {
        'Authorization': apiKey,
        'accept': 'application/json',
      },
    );

    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to load now playing movies');
    }
  }

  Future<Autogenerated> fetchComingSoonMovies() async {
    final response = await http.get(
      Uri.parse(comingSoonApiUrl),
      headers: {
        'Authorization': apiKey,
        'accept': 'application/json',
      },
    );

    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Failed to load coming soon movies');
    }
  }
}
